# Stylesheets that are not written here: `tasks/generate-theme.mjs` copies github-markdown-css and
# highlight.js out of node_modules on every build, so a finding in them cannot be fixed in place,
# and the asciidoctor one is vendored as is. They are already exempt from the license check.
sonar.exclusions=assets/css/github-markdown-css/**,assets/css/highlight.js/**,assets/css/asciidoctor/**,assets/css/gravitee-theme.generated.css
